### ISSUE TITLE
Finalize the humanoid bone set and hierarchy

### ISSUE THREAD

**Issue by takahirox** [takahirox/EXT_skin_humanoid#10]
We must finalize [the humanoid bone set and hierarchy](https://github.com/takahirox/EXT_skeleton_humanoid#humanoid-bone-set-and-hierarchy).

Perhaps it would be good to be based on an existing major skeleton definition.

[VRM humanoid extension](https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0/humanoid.md) may be one of the good options. It is based on glTF and there seems to be many existing VRM models. If the extension is compatible with the VRM humanoid extension, it would help them to convert.

I want this extension to define minimal bone set for standard humanoid skeletal animation. I'm thinking whether face (leftEye, rightEye, and jaw bones) should be in the bone set #8. Facial expression is out of scope from this extension.

Other options may be based on skeletons used in Unity, Unreal engine, Blender, Maya, or so on. We need to research them.

**Comment by hybridherbst** [comment]
I believe the VRM set is strongly based on the Unity mecanim bone set (the original idea was to directly export that to gltf). I think it's a good idea to finalize the ext in a way that VRM is convertible to it.

**Comment by takahirox** [comment]
> based on the Unity mecanim bone set

Is there any web resource where I can check the Unity mecanim bone set?

Yes, bone set based on Unity would be good. (But some people might think it would be a bit too Unity specific?)

**Comment by hybridherbst** [comment]
Some resources:
https://docs.unity3d.com/Manual/class-Avatar.html
https://docs.unity3d.com/Manual/MuscleDefinitions.html

Here's how [Y Bot from Mixamo](https://www.mixamo.com/#/?page=1&query=y+bot&type=Character) gets mapped:

```yaml
    Chest: Spine1
    Head: Head
    Hips: Hips
    Left Index Distal: LeftHandIndex3
    Left Index Intermediate: LeftHandIndex2
    Left Index Proximal: LeftHandIndex1
    Left Little Distal: LeftHandPinky3
    Left Little Intermediate: LeftHandPinky2
    Left Little Proximal: LeftHandPinky1
    Left Middle Distal: LeftHandMiddle3
    Left Middle Intermediate: LeftHandMiddle2
    Left Middle Proximal: LeftHandMiddle1
    Left Ring Distal: LeftHandRing3
    Left Ring Intermediate: LeftHandRing2
    Left Ring Proximal: LeftHandRing1
    Left Thumb Distal: LeftHandThumb3
    Left Thumb Intermediate: LeftHandThumb2
    Left Thumb Proximal: LeftHandThumb1
    LeftFoot: LeftFoot
    LeftHand: LeftHand
    LeftLowerArm: LeftForeArm
    LeftLowerLeg: LeftLeg
    LeftShoulder: LeftShoulder
    LeftToes: LeftToeBase
    LeftUpperArm: LeftArm
    LeftUpperLeg: LeftUpLeg
    Neck: Neck
    Right Index Distal: RightHandIndex3
    Right Index Intermediate: RightHandIndex2
    Right Index Proximal: RightHandIndex1
    Right Little Distal: RightHandPinky3
    Right Little Intermediate: RightHandPinky2
    Right Little Proximal: RightHandPinky1
    Right Middle Distal: RightHandMiddle3
    Right Middle Intermediate: RightHandMiddle2
    Right Middle Proximal: RightHandMiddle1
    Right Ring Distal: RightHandRing3
    Right Ring Intermediate: RightHandRing2
    Right Ring Proximal: RightHandRing1
    Right Thumb Distal: RightHandThumb3
    Right Thumb Intermediate: RightHandThumb2
    Right Thumb Proximal: RightHandThumb1
    RightFoot: RightFoot
    RightHand: RightHand
    RightLowerArm: RightForeArm
    RightLowerLeg: RightLeg
    RightShoulder: RightShoulder
    RightToes: RightToeBase
    RightUpperArm: RightArm
    RightUpperLeg: RightUpLeg
    Spine: Spine
    UpperChest: Spine2
```

Here's a glTF with the Piano Playing animation applied to the rig:
[Y Bot - Piano Playing.zip](https://github.com/takahirox/EXT_skeleton_humanoid/files/10523863/Y.Bot.-.Piano.Playing.zip)

(you can already see that the animation previewing on Mixamo is slightly different, because I did not configure the motion range in Unity perfectly, I just used the automatic mapping here)

And how the mapping setup looks like in Unity - Left Eye / Right Eye / Jaw are also part of the skeleton definition in Unity, which I find very helpful (related to #8).
![20230128-004059_Unity](https://user-images.githubusercontent.com/2693840/215225969-8338dd24-762e-4d10-b2b0-c5d7b1c5a73a.gif)

Hope that helps! We plan on spending more time on Avatars in the near future at Needle, so happy to assist. We want to move away from baking humanoids down (as in the file above, exported from a Unity Humanoid animation) and towards retargeting.
